services:
  - type: web
    name: lingobot2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.index:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
